// <auto-generated />
using System;
using BioDomes.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioDomes.Infrastructures.EntityFramework.Migrations
{
    [DbContext(typeof(BioDomesDbContext))]
    [Migration("20260501185546_UpdateSeedImagePathsToUploads")]
    partial class UpdateSeedImagePathsToUploads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AbsoluteHumidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId", "Name")
                        .IsUnique();

                    b.ToTable("Biomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Biomes_AbsoluteHumidity_NonNegative", "[AbsoluteHumidity] >= 0");

                            t.HasCheckConstraint("CK_Biomes_State_Enum", "[State] IN ('Optimal','Instable','Critique')");

                            t.HasCheckConstraint("CK_Biomes_Temperature_Range", "[Temperature] >= -100");
                        });
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumedElement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsPublicAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ProducedElement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name");

                    b.ToTable("Equipments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Equipment_Name_NotBlank", "[Name] <> ''");

                            t.HasCheckConstraint("CK_Equipment_ProducedOrConsumed_Required", "[ProducedElement] IS NOT NULL OR [ConsumedElement] IS NOT NULL");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumedElement = "Hydrogene",
                            CreatorId = 1,
                            ImagePath = "/uploads/equipment/helio-lamp-a7f3k2q1.jpg",
                            IsPublicAvailable = true,
                            Name = "Helio Lamp A7F3K2Q1",
                            ProducedElement = "Lumiere"
                        },
                        new
                        {
                            Id = 2,
                            ConsumedElement = "Azote",
                            CreatorId = 1,
                            ImagePath = "/uploads/equipment/uv-array-b9m4d8r2.jpg",
                            IsPublicAvailable = true,
                            Name = "UV Array B9M4D8R2",
                            ProducedElement = "Lumiere"
                        },
                        new
                        {
                            Id = 3,
                            ConsumedElement = "Hydrogene",
                            CreatorId = 1,
                            ImagePath = "/uploads/equipment/micro-pump-c6p1t7l5.jpg",
                            IsPublicAvailable = true,
                            Name = "Micro Pump C6P1T7L5",
                            ProducedElement = "Eau"
                        },
                        new
                        {
                            Id = 4,
                            ConsumedElement = "Eau",
                            CreatorId = 1,
                            ImagePath = "/uploads/equipment/nitro-filter-d3x8n4v6.jpg",
                            IsPublicAvailable = true,
                            Name = "Nitro Filter D3X8N4V6",
                            ProducedElement = "Azote"
                        },
                        new
                        {
                            Id = 5,
                            ConsumedElement = "Eau",
                            CreatorId = 1,
                            ImagePath = "/uploads/equipment/hydro-cell-e2r9j5s8.jpg",
                            IsPublicAvailable = true,
                            Name = "Hydro Cell E2R9J5S8",
                            ProducedElement = "Hydrogene"
                        });
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdultSize")
                        .HasColumnType("float");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsPublicAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species", null, t =>
                        {
                            t.HasCheckConstraint("CK_Species_AdultSizeAndWeight_Positive", "[AdultSize] > 0 AND  [Weight] > 0");

                            t.HasCheckConstraint("CK_Species_Name_NotBlank", "[Name] <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultSize = 2.5,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Carnivore",
                            ImagePath = "/uploads/species/lion-dafrique-a1b2c3d4.jpg",
                            IsPublicAvailable = true,
                            Name = "Lion d'Afrique",
                            Weight = 190.0
                        },
                        new
                        {
                            Id = 2,
                            AdultSize = 9.0,
                            Classification = "Plante",
                            CreatorId = 1,
                            Diet = "Photosynthèse",
                            ImagePath = "/uploads/species/monstera-b2c3d4e5.jpg",
                            IsPublicAvailable = true,
                            Name = "Monstera",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 3,
                            AdultSize = 0.94999999999999996,
                            Classification = "Oiseau",
                            CreatorId = 1,
                            Diet = "Herbivore",
                            ImagePath = "/uploads/species/ara-rouge-c3d4e5f6.jpg",
                            IsPublicAvailable = true,
                            Name = "Ara Rouge",
                            Weight = 1.2
                        },
                        new
                        {
                            Id = 4,
                            AdultSize = 1.5,
                            Classification = "Reptile",
                            CreatorId = 1,
                            Diet = "Herbivore",
                            ImagePath = "/uploads/species/tortue-geante-d4e5f6a7.jpg",
                            IsPublicAvailable = true,
                            Name = "Tortue Géante",
                            Weight = 250.0
                        },
                        new
                        {
                            Id = 5,
                            AdultSize = 0.46000000000000002,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Omnivore",
                            ImagePath = "/uploads/species/lemur-catta-e5f6a7b8.jpg",
                            IsPublicAvailable = true,
                            Name = "Lémur Catta",
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            AdultSize = 85.0,
                            Classification = "Plante",
                            CreatorId = 1,
                            Diet = "Photosynthèse",
                            ImagePath = "/uploads/species/sequoia-geant-f6a7b8c9.jpg",
                            IsPublicAvailable = true,
                            Name = "Séquoia Géant",
                            Weight = 1200000.0
                        },
                        new
                        {
                            Id = 7,
                            AdultSize = 0.80000000000000004,
                            Classification = "Plante",
                            CreatorId = 1,
                            Diet = "Photosynthèse",
                            ImagePath = "/uploads/species/aloe-vera-a7b8c9d0.jpg",
                            IsPublicAvailable = true,
                            Name = "Aloe vera",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 8,
                            AdultSize = 1.6000000000000001,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Carnivore",
                            ImagePath = "/uploads/species/loup-gris-b8c9d0e1.jpg",
                            IsPublicAvailable = true,
                            Name = "Loup gris",
                            Weight = 45.0
                        },
                        new
                        {
                            Id = 9,
                            AdultSize = 0.59999999999999998,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Omnivore",
                            ImagePath = "/uploads/species/raton-laveur-c9d0e1f2.jpg",
                            IsPublicAvailable = true,
                            Name = "Raton laveur",
                            Weight = 9.0
                        },
                        new
                        {
                            Id = 10,
                            AdultSize = 2.2000000000000002,
                            Classification = "Reptile",
                            CreatorId = 1,
                            Diet = "Carnivore",
                            ImagePath = "/uploads/species/boa-constrictor-d0e1f2a3.jpg",
                            IsPublicAvailable = true,
                            Name = "Boa constrictor",
                            Weight = 13.0
                        });
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ResearchOrganization")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_BirthDate_NotFuture", "[BirthDate] <= GETDATE()");

                            t.HasCheckConstraint("CK_Users_Role_AllowedValues", "[Role] IN ('User', 'Admin')");
                        });
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeEquipmentLink", b =>
                {
                    b.Property<int>("BiomeId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("BiomeId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("BiomeEquipments", (string)null);
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeSpeciesLink", b =>
                {
                    b.Property<int>("BiomeId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("IndividualCount")
                        .HasColumnType("int");

                    b.HasKey("BiomeId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("BiomeSpecies", null, t =>
                        {
                            t.HasCheckConstraint("CK_BiomeSpecies_IndividualCount_Positive", "[IndividualCount] > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", "Creator")
                        .WithMany("CreatedBiomes")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", "Creator")
                        .WithMany("CreatedEquipments")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", "Creator")
                        .WithMany("CreatedSpecies")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeEquipmentLink", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", "Biome")
                        .WithMany("BiomeEquipmentLinks")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", "Equipment")
                        .WithMany("BiomeEquipmentLinks")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Biome");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeSpeciesLink", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", "Biome")
                        .WithMany("BiomeSpeciesLinks")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", "Species")
                        .WithMany("BiomeSpeciesLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Biome");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", b =>
                {
                    b.Navigation("BiomeEquipmentLinks");

                    b.Navigation("BiomeSpeciesLinks");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", b =>
                {
                    b.Navigation("BiomeEquipmentLinks");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.Navigation("BiomeSpeciesLinks");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedBiomes");

                    b.Navigation("CreatedEquipments");

                    b.Navigation("CreatedSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
