// <auto-generated />
using System;
using BioDomes.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioDomes.Infrastructures.EntityFramework.Migrations
{
    [DbContext(typeof(BioDomesDbContext))]
    [Migration("20260409165905_ImplementationEntitiesV1")]
    partial class ImplementationEntitiesV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AbsoluteHumidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId", "Name")
                        .IsUnique();

                    b.ToTable("Biomes", (string)null);
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumedElement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsPublicAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ProducedElement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name");

                    b.ToTable("Equipments", (string)null);
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdultSize")
                        .HasColumnType("float");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsPublicAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultSize = 2.5,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Carnivore",
                            ImagePath = "/images/species/lion-dafrique-a1b2c3d4.jpg",
                            IsPublicAvailable = true,
                            Name = "Lion d'Afrique",
                            Weight = 190.0
                        },
                        new
                        {
                            Id = 2,
                            AdultSize = 9.0,
                            Classification = "Plante",
                            CreatorId = 1,
                            Diet = "Photosynthèse",
                            ImagePath = "/images/species/monstera-b2c3d4e5.jpg",
                            IsPublicAvailable = true,
                            Name = "Monstera",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 3,
                            AdultSize = 0.94999999999999996,
                            Classification = "Oiseau",
                            CreatorId = 1,
                            Diet = "Herbivore",
                            ImagePath = "/images/species/ara-rouge-c3d4e5f6.jpg",
                            IsPublicAvailable = true,
                            Name = "Ara Rouge",
                            Weight = 1.2
                        },
                        new
                        {
                            Id = 4,
                            AdultSize = 1.5,
                            Classification = "Reptile",
                            CreatorId = 1,
                            Diet = "Herbivore",
                            ImagePath = "/images/species/tortue-geante-d4e5f6a7.jpg",
                            IsPublicAvailable = true,
                            Name = "Tortue Géante",
                            Weight = 250.0
                        },
                        new
                        {
                            Id = 5,
                            AdultSize = 0.46000000000000002,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Omnivore",
                            ImagePath = "/images/species/lemur-catta-e5f6a7b8.jpg",
                            IsPublicAvailable = true,
                            Name = "Lémur Catta",
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            AdultSize = 85.0,
                            Classification = "Plante",
                            CreatorId = 1,
                            Diet = "Photosynthèse",
                            ImagePath = "/images/species/sequoia-geant-f6a7b8c9.jpg",
                            IsPublicAvailable = true,
                            Name = "Séquoia Géant",
                            Weight = 1200000.0
                        },
                        new
                        {
                            Id = 7,
                            AdultSize = 0.80000000000000004,
                            Classification = "Plante",
                            CreatorId = 1,
                            Diet = "Photosynthèse",
                            ImagePath = "/images/species/aloe-vera-a7b8c9d0.jpg",
                            IsPublicAvailable = true,
                            Name = "Aloe vera",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 8,
                            AdultSize = 1.6000000000000001,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Carnivore",
                            ImagePath = "/images/species/loup-gris-b8c9d0e1.jpg",
                            IsPublicAvailable = true,
                            Name = "Loup gris",
                            Weight = 45.0
                        },
                        new
                        {
                            Id = 9,
                            AdultSize = 0.59999999999999998,
                            Classification = "Mammifère",
                            CreatorId = 1,
                            Diet = "Omnivore",
                            ImagePath = "/images/species/raton-laveur-c9d0e1f2.jpg",
                            IsPublicAvailable = true,
                            Name = "Raton laveur",
                            Weight = 9.0
                        },
                        new
                        {
                            Id = 10,
                            AdultSize = 2.2000000000000002,
                            Classification = "Reptile",
                            CreatorId = 1,
                            Diet = "Carnivore",
                            ImagePath = "/images/species/boa-constrictor-d0e1f2a3.jpg",
                            IsPublicAvailable = true,
                            Name = "Boa constrictor",
                            Weight = 13.0
                        });
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResearchOrganization")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 1, 1),
                            Email = "admin@biodomes.local",
                            PasswordHash = "seed-admin-password-hash",
                            ResearchOrganization = "Laudot Solutions",
                            Role = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeEquipmentLink", b =>
                {
                    b.Property<int>("BiomeId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("BiomeId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("BiomeEquipments", (string)null);
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeSpeciesLink", b =>
                {
                    b.Property<int>("BiomeId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("IndividualCount")
                        .HasColumnType("int");

                    b.HasKey("BiomeId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("BiomeSpecies", (string)null);
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", "Creator")
                        .WithMany("CreatedBiomes")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", "Creator")
                        .WithMany("CreatedEquipments")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", "Creator")
                        .WithMany("CreatedSpecies")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeEquipmentLink", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", "Biome")
                        .WithMany("BiomeEquipmentLinks")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", "Equipment")
                        .WithMany("BiomeEquipmentLinks")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Biome");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Links.BiomeSpeciesLink", b =>
                {
                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", "Biome")
                        .WithMany("BiomeSpeciesLinks")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", "Species")
                        .WithMany("BiomeSpeciesLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Biome");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.BiomeEntity", b =>
                {
                    b.Navigation("BiomeEquipmentLinks");

                    b.Navigation("BiomeSpeciesLinks");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.EquipmentEntity", b =>
                {
                    b.Navigation("BiomeEquipmentLinks");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.Navigation("BiomeSpeciesLinks");
                });

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedBiomes");

                    b.Navigation("CreatedEquipments");

                    b.Navigation("CreatedSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
