// <auto-generated />
using BioDomes.Infrastructures.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioDomes.Infrastructures.EntityFramework.Migrations
{
    [DbContext(typeof(BioDomesDbContext))]
    [Migration("20260319225709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdultSize")
                        .HasColumnType("REAL");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Species", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultSize = 2.5,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Carnivore",
                            IsPublic = true,
                            Name = "Lion d'Afrique",
                            Weight = 190.0
                        },
                        new
                        {
                            Id = 2,
                            AdultSize = 9.0,
                            Classification = "Plante",
                            CreatedByUserName = "admin",
                            Diet = "Photosynthèse",
                            IsPublic = true,
                            Name = "Monstera",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 3,
                            AdultSize = 0.94999999999999996,
                            Classification = "Oiseau",
                            CreatedByUserName = "admin",
                            Diet = "Herbivore",
                            IsPublic = true,
                            Name = "Ara Rouge",
                            Weight = 1.2
                        },
                        new
                        {
                            Id = 4,
                            AdultSize = 1.5,
                            Classification = "Reptile",
                            CreatedByUserName = "admin",
                            Diet = "Herbivore",
                            IsPublic = true,
                            Name = "Tortue Géante",
                            Weight = 250.0
                        },
                        new
                        {
                            Id = 5,
                            AdultSize = 0.46000000000000002,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Omnivore",
                            IsPublic = true,
                            Name = "Lémur Catta",
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            AdultSize = 85.0,
                            Classification = "Plante",
                            CreatedByUserName = "admin",
                            Diet = "Photosynthèse",
                            IsPublic = true,
                            Name = "Séquoia Géant",
                            Weight = 1200000.0
                        },
                        new
                        {
                            Id = 7,
                            AdultSize = 0.80000000000000004,
                            Classification = "Plante",
                            CreatedByUserName = "admin",
                            Diet = "Photosynthèse",
                            IsPublic = true,
                            Name = "Aloe vera",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 8,
                            AdultSize = 1.6000000000000001,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Carnivore",
                            IsPublic = true,
                            Name = "Loup gris",
                            Weight = 45.0
                        },
                        new
                        {
                            Id = 9,
                            AdultSize = 0.59999999999999998,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Omnivore",
                            IsPublic = true,
                            Name = "Raton laveur",
                            Weight = 9.0
                        },
                        new
                        {
                            Id = 10,
                            AdultSize = 2.2000000000000002,
                            Classification = "Reptile",
                            CreatedByUserName = "admin",
                            Diet = "Carnivore",
                            IsPublic = true,
                            Name = "Boa constrictor",
                            Weight = 13.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
