// <auto-generated />
using BioDomes.Infrastructures.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioDomes.Infrastructures.EntityFramework.Migrations
{
    [DbContext(typeof(BioDomesDbContext))]
    partial class BioDomesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BioDomes.Infrastructures.EntityFramework.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdultSize")
                        .HasColumnType("float");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Species", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultSize = 2.5,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Carnivore",
                            ImagePath = "/images/species/lion-dafrique-a1b2c3d4.jpg",
                            IsPublic = true,
                            Name = "Lion d'Afrique",
                            Weight = 190.0
                        },
                        new
                        {
                            Id = 2,
                            AdultSize = 9.0,
                            Classification = "Plante",
                            CreatedByUserName = "admin",
                            Diet = "Photosynthèse",
                            ImagePath = "/images/species/monstera-b2c3d4e5.jpg",
                            IsPublic = true,
                            Name = "Monstera",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 3,
                            AdultSize = 0.94999999999999996,
                            Classification = "Oiseau",
                            CreatedByUserName = "admin",
                            Diet = "Herbivore",
                            ImagePath = "/images/species/ara-rouge-c3d4e5f6.jpg",
                            IsPublic = true,
                            Name = "Ara Rouge",
                            Weight = 1.2
                        },
                        new
                        {
                            Id = 4,
                            AdultSize = 1.5,
                            Classification = "Reptile",
                            CreatedByUserName = "admin",
                            Diet = "Herbivore",
                            ImagePath = "/images/species/tortue-geante-d4e5f6a7.jpg",
                            IsPublic = true,
                            Name = "Tortue Géante",
                            Weight = 250.0
                        },
                        new
                        {
                            Id = 5,
                            AdultSize = 0.46000000000000002,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Omnivore",
                            ImagePath = "/images/species/lemur-catta-e5f6a7b8.jpg",
                            IsPublic = true,
                            Name = "Lémur Catta",
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            AdultSize = 85.0,
                            Classification = "Plante",
                            CreatedByUserName = "admin",
                            Diet = "Photosynthèse",
                            ImagePath = "/images/species/sequoia-geant-f6a7b8c9.jpg",
                            IsPublic = true,
                            Name = "Séquoia Géant",
                            Weight = 1200000.0
                        },
                        new
                        {
                            Id = 7,
                            AdultSize = 0.80000000000000004,
                            Classification = "Plante",
                            CreatedByUserName = "admin",
                            Diet = "Photosynthèse",
                            ImagePath = "/images/species/aloe-vera-a7b8c9d0.jpg",
                            IsPublic = true,
                            Name = "Aloe vera",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 8,
                            AdultSize = 1.6000000000000001,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Carnivore",
                            ImagePath = "/images/species/loup-gris-b8c9d0e1.jpg",
                            IsPublic = true,
                            Name = "Loup gris",
                            Weight = 45.0
                        },
                        new
                        {
                            Id = 9,
                            AdultSize = 0.59999999999999998,
                            Classification = "Mammifère",
                            CreatedByUserName = "admin",
                            Diet = "Omnivore",
                            ImagePath = "/images/species/raton-laveur-c9d0e1f2.jpg",
                            IsPublic = true,
                            Name = "Raton laveur",
                            Weight = 9.0
                        },
                        new
                        {
                            Id = 10,
                            AdultSize = 2.2000000000000002,
                            Classification = "Reptile",
                            CreatedByUserName = "admin",
                            Diet = "Carnivore",
                            ImagePath = "/images/species/boa-constrictor-d0e1f2a3.jpg",
                            IsPublic = true,
                            Name = "Boa constrictor",
                            Weight = 13.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
